name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar:
    uses: scottobert/deployment-pipeline/.github/workflows/sonar.yml@main
    with:
      node-version: '20'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: sonar
    if: github.event_name == 'push'
    uses: scottobert/deployment-pipeline/.github/workflows/semantic-release.yml@main
    with:
      node-version: '20'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
